# -*- coding: utf-8 -*-
"""weather_data_cleaning01_merge_data_by_year.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBIqN-3u2daP9AmWFTJ5MXIVRP5BcAGf
"""

# --- Colab: Mount Drive ---
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
from pathlib import Path

# --- Paths (edit if needed) ---
BASE_DIR = Path("/content/drive/MyDrive/946dataWeather_ON")
IDS_FILE = BASE_DIR / "on_station_ids.txt"

# --- Load station ids ---
with open(IDS_FILE, "r") as f:
    station_ids = [line.strip() for line in f if line.strip()]

print(f"Loaded {len(station_ids)} station IDs")

# --- Config ---
YEARS = list(range(2020, 2026))
OUT_DIR = BASE_DIR / "merged_by_year"
OUT_DIR.mkdir(parents=True, exist_ok=True)

def read_station_year_csv(station_id: str, year: int) -> pd.DataFrame | None:
    """
    Reads one station-year CSV if it exists and returns a DataFrame.
    Adds station_id + year columns for easier analysis.
    """
    station_folder = BASE_DIR / f"station_{station_id}"
    csv_path = station_folder / f"station_{station_id}_daily_{year}.csv"
    if not csv_path.exists():
        return None

    df = pd.read_csv(csv_path)
    df["station_id"] = station_id
    df["year"] = year
    return df

merged_by_year = {}

for year in YEARS:
    dfs = []
    missing = 0

    for sid in station_ids:
        df = read_station_year_csv(sid, year)
        if df is None:
            missing += 1
            continue
        dfs.append(df)

    if not dfs:
        print(f"[{year}] No files found.")
        continue

    merged = pd.concat(dfs, ignore_index=True)

    # Optional: if your sheet has a date column, parse it (uncomment + adjust name)
    # merged["date"] = pd.to_datetime(merged["date"], errors="coerce")

    out_path = OUT_DIR / f"ON_weather_daily_merged_{year}.csv"
    merged.to_csv(out_path, index=False)

    merged_by_year[year] = merged
    print(f"[{year}] merged rows={len(merged):,} | stations loaded={len(dfs):,} | missing stations={missing:,}")
    print(f"      saved -> {out_path}")

# Optional: merge all years into one DataFrame (if you want)
if merged_by_year:
    all_years_df = pd.concat(list(merged_by_year.values()), ignore_index=True)
    all_out = OUT_DIR / "ON_weather_daily_merged_2020_2025.csv"
    all_years_df.to_csv(all_out, index=False)
    print(f"\nAll-years merged rows={len(all_years_df):,} saved -> {all_out}")